'use client';

import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import Link from 'next/link';

type TabType = 'privacy' | 'terms' | 'disclaimer';

export default function LegalPage() {
  const [activeTab, setActiveTab] = useState<TabType>('disclaimer');

  const tabs = [
    { id: 'disclaimer' as TabType, label: 'Disclaimer' },
    { id: 'privacy' as TabType, label: 'Privacy Policy' },
    { id: 'terms' as TabType, label: 'Terms of Service' },
  ];

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-8">
          <Link href="/" className="text-blue-400 hover:text-blue-300 flex items-center gap-2">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Dashboard
          </Link>
        </div>

        <h1 className="text-3xl font-bold text-white mb-8">Legal Information</h1>

        <div className="flex gap-2 mb-6">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                activeTab === tab.id
                  ? 'bg-blue-600 text-white'
                  : 'bg-white/10 text-slate-300 hover:bg-white/20'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <Card className="p-8 bg-white/5 border-white/10">
          {activeTab === 'disclaimer' && (
            <div className="prose prose-invert max-w-none">
              <h2 className="text-2xl font-bold text-white mb-4">Disclaimer</h2>
              
              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Investment Disclaimer</h3>
              <p className="text-slate-300 mb-4">
                TickerGrade is provided for <strong>educational and informational purposes only</strong>. The content, analysis, scores, and recommendations generated by this application do not constitute financial, investment, tax, or legal advice.
              </p>
              <p className="text-slate-300 mb-4">
                All investment strategies and investments involve risk of loss. Nothing contained in this application should be construed as investment advice. Any reference to an investment's past or potential performance is not, and should not be construed as, a recommendation or guarantee of any specific outcome or profit.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">No Warranty</h3>
              <p className="text-slate-300 mb-4">
                The information provided by TickerGrade is provided "as is" without any representations or warranties, express or implied. We make no representations or warranties in relation to the financial information or other content on this application.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Data Attribution</h3>
              <div className="bg-yellow-500/10 border border-yellow-500/30 p-4 rounded-lg mb-4">
                <p className="text-yellow-200">
                  <strong>Option-Adjusted Spread (OAS) data is sourced from ICE Data Indices, LLC, used with permission via FRED®.</strong>
                </p>
              </div>
              <p className="text-slate-300 mb-4">
                This product uses the FRED® API but is not endorsed or certified by the Federal Reserve Bank of St. Louis.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Consult a Professional</h3>
              <p className="text-slate-300">
                Before making any investment decisions, you should consult with a qualified financial advisor who can provide personalized advice based on your individual circumstances.
              </p>
            </div>
          )}

          {activeTab === 'privacy' && (
            <div className="prose prose-invert max-w-none">
              <h2 className="text-2xl font-bold text-white mb-4">Privacy Policy</h2>
              
              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Information We Collect</h3>
              <p className="text-slate-300 mb-4">
                We collect information you provide directly to us when you:
              </p>
              <ul className="list-disc list-inside text-slate-300 mb-4 space-y-2">
                <li>Create an account or log in using Replit authentication</li>
                <li>Use our stock analysis features</li>
                <li>Contact us with questions or feedback</li>
              </ul>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">How We Use Your Information</h3>
              <p className="text-slate-300 mb-4">
                We use the information we collect to:
              </p>
              <ul className="list-disc list-inside text-slate-300 mb-4 space-y-2">
                <li>Provide, maintain, and improve our services</li>
                <li>Authenticate your identity and manage your account</li>
                <li>Respond to your comments and questions</li>
              </ul>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Cookies</h3>
              <p className="text-slate-300 mb-4">
                We use cookies for authentication purposes and to improve your experience. By using our application, you consent to the use of cookies.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Data Security</h3>
              <p className="text-slate-300">
                We implement appropriate security measures to protect your personal information. However, no method of transmission over the Internet is 100% secure.
              </p>
            </div>
          )}

          {activeTab === 'terms' && (
            <div className="prose prose-invert max-w-none">
              <h2 className="text-2xl font-bold text-white mb-4">Terms of Service</h2>
              
              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Acceptance of Terms</h3>
              <p className="text-slate-300 mb-4">
                By accessing and using TickerGrade, you accept and agree to be bound by the terms and provisions of this agreement.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Use of Service</h3>
              <p className="text-slate-300 mb-4">
                You agree to use the service only for lawful purposes and in accordance with these Terms. You agree not to:
              </p>
              <ul className="list-disc list-inside text-slate-300 mb-4 space-y-2">
                <li>Use the service in any way that violates any applicable law or regulation</li>
                <li>Attempt to gain unauthorized access to any portion of the service</li>
                <li>Use any automated means to access the service for any purpose</li>
                <li>Redistribute or resell the analysis or data provided by the service</li>
              </ul>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Intellectual Property</h3>
              <p className="text-slate-300 mb-4">
                The service and its original content, features, and functionality are owned by the operators and are protected by international copyright, trademark, and other intellectual property laws.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Limitation of Liability</h3>
              <p className="text-slate-300 mb-4">
                In no event shall the operators be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, or other intangible losses, resulting from your use of the service.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Changes to Terms</h3>
              <p className="text-slate-300">
                We reserve the right to modify or replace these Terms at any time. Your continued use of the service after any such changes constitutes your acceptance of the new Terms.
              </p>
            </div>
          )}
        </Card>
      </div>
    </main>
  );
}
